{% set name = "dagster_papertrail" %}
{% set version = "0.6.7.post0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name|replace('_', '-') }}/{{ name|replace('_', '-') }}-{{ version }}.tar.gz"
  sha256: e22d107ddd96cad876783041cd85da69b0d71357f993bfe3d88b95c5f6d5809f

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - dagster {{ version }}.*

test:
  imports:
    - dagster_papertrail

about:
  home: "https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-papertrail"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "Package for papertrail Dagster framework components."

extra:
  recipe-maintainers:
    - conda-forge/dagster
