{% set name = "dagster_papertrail" %}
{% set version = "0.6.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 7e20db76991b4982dfc290a6a40c9ff8b2be08fd8d7faf68895d1dea57fea597

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - dagster {{ version }}.*

test:
  imports:
    - dagster_papertrail

about:
  home: "https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-papertrail"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "Package for papertrail Dagster framework components."

extra:
  recipe-maintainers:
    - conda-forge/dagster
